### ISSUE TITLE
Read sensors trouble

### ISSUE THREAD

**Issue by al3sh** [steventwheeler/libroomba#2]
Hi, 
I’m using lib roomba library, I can control the roomba fine, but when Trying to read the sensors , the values are strange.
Ex. Voltage is always 65535, and not changing a bit.
       Current is -1
       Other values are 1 or -1

Any ideas how to fix this ?
Tnx

**Comment by steventwheeler** [comment]
Are you calling `Libroomba::updateSensors()` prior to reading the sensor data? If not then the array which is used to store the sensor data bytes won't have been initialized.

**Comment by steventwheeler** [comment]
I just set up my 870 to test and can confirm that both the current and voltage values are reported after calling the `Libroomba::updateSensors()` function.

**Comment by steventwheeler** [comment]
Since there's been no follow up I'm going to assume this is resolved.
